apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc1
  labels:
    type: nfs
spec:
  storageClassName: managed-nfs-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /srv/k8s
    server: 192.168.1.158